# Generated by Django 3.2.8 on 2021-10-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_part', '0002_advertisingcosts_chibadoyukai'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitycosts_comunicationcosts',
            name='ubiregi_nhk',
            field=models.IntegerField(blank=True, null=True, verbose_name='ユビレジ/NHK料金'),
        ),
    ]
