# Generated by Django 3.2.8 on 2021-11-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_part', '0005_auto_20211125_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laborcosts',
            old_name='labor9',
            new_name='transportationExpenses',
        ),
    ]
