# Generated by Django 3.2.8 on 2021-11-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_part', '0007_auto_20211126_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisingcosts',
            name='ad15',
            field=models.IntegerField(blank=True, null=True, verbose_name='外販委託料2'),
        ),
        migrations.AlterField(
            model_name='advertisingcosts',
            name='ad7',
            field=models.IntegerField(blank=True, null=True, verbose_name='食べログ2'),
        ),
        migrations.AlterField(
            model_name='drinkcosts',
            name='drink6',
            field=models.IntegerField(blank=True, null=True, verbose_name='大崎商店2'),
        ),
        migrations.AlterField(
            model_name='drinkcosts',
            name='drink7',
            field=models.IntegerField(blank=True, null=True, verbose_name='大崎商店3'),
        ),
        migrations.AlterField(
            model_name='foodcosts',
            name='food10',
            field=models.IntegerField(blank=True, null=True, verbose_name='笹本ミート4'),
        ),
        migrations.AlterField(
            model_name='foodcosts',
            name='food14',
            field=models.IntegerField(blank=True, null=True, verbose_name='ナミキ農場2'),
        ),
        migrations.AlterField(
            model_name='foodcosts',
            name='food16',
            field=models.IntegerField(blank=True, null=True, verbose_name='岩井カレー2'),
        ),
        migrations.AlterField(
            model_name='foodcosts',
            name='food18',
            field=models.IntegerField(blank=True, null=True, verbose_name='クマガヤフーズ2'),
        ),
        migrations.AlterField(
            model_name='foodcosts',
            name='food19',
            field=models.IntegerField(blank=True, null=True, verbose_name='クマガヤフーズ3'),
        ),
        migrations.AlterField(
            model_name='foodcosts',
            name='food23',
            field=models.IntegerField(blank=True, null=True, verbose_name='西川商会2'),
        ),
        migrations.AlterField(
            model_name='foodcosts',
            name='food25',
            field=models.IntegerField(blank=True, null=True, verbose_name='東海2'),
        ),
        migrations.AlterField(
            model_name='foodcosts',
            name='food26',
            field=models.IntegerField(blank=True, null=True, verbose_name='東海3'),
        ),
        migrations.AlterField(
            model_name='foodcosts',
            name='food8',
            field=models.IntegerField(blank=True, null=True, verbose_name='笹本ミート2'),
        ),
        migrations.AlterField(
            model_name='foodcosts',
            name='food9',
            field=models.IntegerField(blank=True, null=True, verbose_name='笹本ミート3'),
        ),
        migrations.AlterField(
            model_name='othercosts',
            name='other6',
            field=models.IntegerField(blank=True, null=True, verbose_name='消耗品2'),
        ),
        migrations.AlterField(
            model_name='othercosts',
            name='other8',
            field=models.IntegerField(blank=True, null=True, verbose_name='消耗費3'),
        ),
        migrations.AlterField(
            model_name='taxexemptexpenses',
            name='tax18',
            field=models.IntegerField(blank=True, null=True, verbose_name='クレジットカード手数料2'),
        ),
        migrations.AlterField(
            model_name='taxexemptexpenses',
            name='tax19',
            field=models.IntegerField(blank=True, null=True, verbose_name='クレジットカード手数料3'),
        ),
        migrations.AlterField(
            model_name='taxexemptexpenses',
            name='tax20',
            field=models.IntegerField(blank=True, null=True, verbose_name='クレジットカード手数料4'),
        ),
        migrations.AlterField(
            model_name='utilitycosts_comunicationcosts',
            name='util11',
            field=models.IntegerField(blank=True, null=True, verbose_name='水道節水費2'),
        ),
        migrations.AlterField(
            model_name='utilitycosts_comunicationcosts',
            name='util19',
            field=models.IntegerField(blank=True, null=True, verbose_name='フィルコム2'),
        ),
        migrations.AlterField(
            model_name='utilitycosts_comunicationcosts',
            name='util7',
            field=models.IntegerField(blank=True, null=True, verbose_name='電気節電費2'),
        ),
        migrations.AlterField(
            model_name='utilitycosts_comunicationcosts',
            name='util8',
            field=models.IntegerField(blank=True, null=True, verbose_name='電気節電費3'),
        ),
        migrations.AlterField(
            model_name='utilitycosts_comunicationcosts',
            name='util9',
            field=models.IntegerField(blank=True, null=True, verbose_name='電気節電費4'),
        ),
    ]
