from django.db import models


class PL_data(models.Model):
    y_m = models.CharField("日付", null=False, default=199901, max_length=6)
    category = models.CharField("カテゴリー", null=False, default="カテゴリ", max_length=30)
    amountSold = models.IntegerField(verbose_name="総売上高", null=True, blank=True)
    rent = models.IntegerField("家賃", null=True, blank=True)

    def __str__(self):
        # return self.category + str(self.y_m)
        return self.category


class FoodCosts(models.Model):
    pl_data = models.ForeignKey(PL_data, on_delete=models.CASCADE)
    cash_purchase_food = models.IntegerField("現金仕入れ(フード)", null=True, blank=True)
    food1 = models.IntegerField("サイトウフード", null=True, blank=True)
    food2 = models.IntegerField("タカハシフード", null=True, blank=True)
    food3 = models.IntegerField("かみやま水産", null=True, blank=True)
    food4 = models.IntegerField("山村水産", null=True, blank=True)
    food5 = models.IntegerField("メトロ(フード)", null=True, blank=True)
    food6 = models.IntegerField("メトロ", null=True, blank=True)
    food7 = models.IntegerField("笹本ミート", null=True, blank=True)
    food8 = models.IntegerField("笹本ミート2", null=True, blank=True)
    food9 = models.IntegerField("笹本ミート3", null=True, blank=True)
    food10 = models.IntegerField("笹本ミート4", null=True, blank=True)
    food11 = models.IntegerField("イシイ", null=True, blank=True)
    food12 = models.IntegerField("サニープロダクツ", null=True, blank=True)
    food13 = models.IntegerField("ナミキ農場", null=True, blank=True)
    food14 = models.IntegerField("ナミキ農場2", null=True, blank=True)
    food15 = models.IntegerField("岩井カレー", null=True, blank=True)
    food16 = models.IntegerField("岩井カレー2", null=True, blank=True)
    food17 = models.IntegerField("クマガヤフーズ", null=True, blank=True)
    food18 = models.IntegerField("クマガヤフーズ2", null=True, blank=True)
    food19 = models.IntegerField("クマガヤフーズ3", null=True, blank=True)
    food20 = models.IntegerField("八百や", null=True, blank=True)
    food21 = models.IntegerField("ベジタリアン", null=True, blank=True)
    food22 = models.IntegerField("西川商会", null=True, blank=True)
    food23 = models.IntegerField("西川商会2", null=True, blank=True)
    food24 = models.IntegerField("東海", null=True, blank=True)
    food25 = models.IntegerField("東海2", null=True, blank=True)
    food26 = models.IntegerField("東海3", null=True, blank=True)
    food27 = models.IntegerField("ますだフーズ", null=True, blank=True)
    food28 = models.IntegerField("平野園", null=True, blank=True)
    food29 = models.IntegerField("サンローラン", null=True, blank=True)
    food30 = models.IntegerField("丸フード", null=True, blank=True)


class DrinkCosts(models.Model):
    pl_data = models.ForeignKey(PL_data, on_delete=models.CASCADE)
    drink2 = models.IntegerField("藤川リカー", null=True, blank=True)
    drink3 = models.IntegerField("山野酒店", null=True, blank=True)
    drink4 = models.IntegerField("ネス", null=True, blank=True)
    drink5 = models.IntegerField("大崎商店", null=True, blank=True)
    drink6 = models.IntegerField("大崎商店2", null=True, blank=True)
    drink7 = models.IntegerField("大崎商店3", null=True, blank=True)
    drink8 = models.IntegerField("マキコーポレーション", null=True, blank=True)
    drink9 = models.IntegerField("ピージャパン", null=True, blank=True)
    drink10 = models.IntegerField("酒のさかもと", null=True, blank=True)
    drink11 = models.IntegerField("その他(ドリンク)", null=True, blank=True)


class LaborCosts(models.Model):
    pl_data = models.ForeignKey(PL_data, on_delete=models.CASCADE)
    labor2 = models.IntegerField("人件費", null=True, blank=True)
    labor3 = models.IntegerField("社員人件費", null=True, blank=True)
    labor4 = models.IntegerField("アルバイト人件費", null=True, blank=True)
    labor5 = models.IntegerField("社保合計", null=True, blank=True)
    labor6 = models.IntegerField("その他（日払い等）", null=True, blank=True)
    labor7 = models.IntegerField("賞与社保合計/その他（日払い等）", null=True, blank=True)
    labor8 = models.IntegerField("賞与", null=True, blank=True)
    transportationExpenses = models.IntegerField("交通費", null=True, blank=True)


class UtilityCosts_ComunicationCosts(models.Model):
    pl_data = models.ForeignKey(PL_data, on_delete=models.CASCADE)
    util2 = models.IntegerField("ガス代", null=True, blank=True)
    util3 = models.IntegerField("電気代", null=True, blank=True)
    util4 = models.IntegerField("上水道代", null=True, blank=True)
    util5 = models.IntegerField("下水道", null=True, blank=True)
    util6 = models.IntegerField("電気節電費", null=True, blank=True)
    util7 = models.IntegerField("電気節電費2", null=True, blank=True)
    util8 = models.IntegerField("電気節電費3", null=True, blank=True)
    util9 = models.IntegerField("電気節電費4", null=True, blank=True)
    util10 = models.IntegerField("水道節水費", null=True, blank=True)
    util11 = models.IntegerField("水道節水費2", null=True, blank=True)
    util12 = models.IntegerField("通信費", null=True, blank=True)
    util13 = models.IntegerField("ぽすレジ", null=True, blank=True)
    util14 = models.IntegerField("有線", null=True, blank=True)
    util15 = models.IntegerField("ネット代", null=True, blank=True)
    util16 = models.IntegerField("NHK料金", null=True, blank=True)
    util17 = models.IntegerField("残存割賦金", null=True, blank=True)
    util18 = models.IntegerField("フィルコム", null=True, blank=True)
    util19 = models.IntegerField("フィルコム2", null=True, blank=True)
    util20 = models.IntegerField("ライセンスフィー", null=True, blank=True)
    util21 = models.IntegerField("借家ガス代", null=True, blank=True)


class AdvertisingCosts(models.Model):
    pl_data = models.ForeignKey(PL_data, on_delete=models.CASCADE)
    ad2 = models.IntegerField("広告費（ぐるなび）", null=True, blank=True)
    ad3 = models.IntegerField("ぐるなび", null=True, blank=True)
    ad4 = models.IntegerField("広告費（ＨＰ）", null=True, blank=True)
    ad5 = models.IntegerField("ホットペッパー", null=True, blank=True)
    ad6 = models.IntegerField("食べログ", null=True, blank=True)
    ad7 = models.IntegerField("食べログ2", null=True, blank=True)
    ad8 = models.IntegerField("広告費", null=True, blank=True)
    ad9 = models.IntegerField("トサラ", null=True, blank=True)
    ad10 = models.IntegerField("本部", null=True, blank=True)
    ad11 = models.IntegerField("レッティー", null=True, blank=True)
    ad12 = models.IntegerField("本部", null=True, blank=True)
    ad13 = models.IntegerField("UBER", null=True, blank=True)
    ad14 = models.IntegerField("外販委託料", null=True, blank=True)
    ad15 = models.IntegerField("外販委託料2", null=True, blank=True)
    ad16 = models.IntegerField("グーグル広告", null=True, blank=True)
    ad17 = models.IntegerField("求人広告費", null=True, blank=True)
    ad18 = models.IntegerField("会費", null=True, blank=True)


class OtherCosts(models.Model):
    pl_data = models.ForeignKey(PL_data, on_delete=models.CASCADE)
    other2 = models.IntegerField("アクスル", null=True, blank=True)
    other3 = models.IntegerField("プレティ", null=True, blank=True)
    other4 = models.IntegerField("消耗品", null=True, blank=True)
    other5 = models.IntegerField("レジリース代", null=True, blank=True)
    other6 = models.IntegerField("消耗品2", null=True, blank=True)
    other7 = models.IntegerField("その他", null=True, blank=True)
    other8 = models.IntegerField("消耗費3", null=True, blank=True)
    other9 = models.IntegerField("ごみ処理費", null=True, blank=True)
    other10 = models.IntegerField("お絞り代", null=True, blank=True)
    other11 = models.IntegerField("害虫駆除", null=True, blank=True)
    other12 = models.IntegerField("排水管清掃", null=True, blank=True)
    other13 = models.IntegerField("ダフィル", null=True, blank=True)
    other14 = models.IntegerField("アルト", null=True, blank=True)
    other15 = models.IntegerField("設備リース", null=True, blank=True)
    other16 = models.IntegerField("会議費", null=True, blank=True)
    other17 = models.IntegerField("他店視察費", null=True, blank=True)
    other18 = models.IntegerField("接待交際費", null=True, blank=True)
    other19 = models.IntegerField("福利厚生費", null=True, blank=True)
    other20 = models.IntegerField("設備投資(備品、修理等、その他)", null=True, blank=True)
    other21 = models.IntegerField("住宅手当", null=True, blank=True)
    other22 = models.IntegerField("社宅手当", null=True, blank=True)
    other23 = models.IntegerField("駐車場代", null=True, blank=True)
    other24 = models.IntegerField("車両費", null=True, blank=True)
    other25 = models.IntegerField("労務士報酬", null=True, blank=True)
    other26 = models.IntegerField("税理士報酬", null=True, blank=True)
    other27 = models.IntegerField("家賃　更新代", null=True, blank=True)
    other28 = models.IntegerField("家賃　更新代 補償金", null=True, blank=True)
    other29 = models.IntegerField("補助金", null=True, blank=True)


class TaxExemptExpenses(models.Model):
    pl_data = models.ForeignKey(PL_data, on_delete=models.CASCADE)
    tax1 = models.IntegerField("保険料（店舗・自動車・労災・車検）", null=True, blank=True)
    tax2 = models.IntegerField("保険料（店舗・自動車・労災）", null=True, blank=True)
    tax3 = models.IntegerField("返済", null=True, blank=True)
    tax4 = models.IntegerField("保険料/（店舗・自動車・労災）", null=True, blank=True)
    tax5 = models.IntegerField("①返済", null=True, blank=True)
    tax6 = models.IntegerField("②返済", null=True, blank=True)
    tax7 = models.IntegerField("③返済", null=True, blank=True)
    tax8 = models.IntegerField("④返済", null=True, blank=True)
    tax9 = models.IntegerField("①プデシル", null=True, blank=True)
    tax10 = models.IntegerField("②プデシル", null=True, blank=True)
    tax11 = models.IntegerField("①クレジットカード手数料", null=True, blank=True)
    tax12 = models.IntegerField("②クレジットカード手数料", null=True, blank=True)
    tax13 = models.IntegerField("租税効果(法人税・住民税等)", null=True, blank=True)
    tax14 = models.IntegerField("保険料（店舗・労災）", null=True, blank=True)
    tax15 = models.IntegerField("保険料（自動車・車検）", null=True, blank=True)
    tax16 = models.IntegerField("倒産防止共済", null=True, blank=True)
    tax17 = models.IntegerField("クレジットカード手数料", null=True, blank=True)
    tax18 = models.IntegerField("クレジットカード手数料2", null=True, blank=True)
    tax19 = models.IntegerField("クレジットカード手数料3", null=True, blank=True)
    tax20 = models.IntegerField("クレジットカード手数料4", null=True, blank=True)

