# Generated by Django 3.2.8 on 2021-10-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetFileName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(default='店名', max_length=30)),
                ('file_name', models.CharField(default='店名', max_length=100)),
            ],
        ),
    ]
