# Generated by Django 3.2.8 on 2021-10-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0002_targetfilename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(default='店名', max_length=30)),
                ('salary', models.IntegerField(default=0, verbose_name='社員給料')),
                ('hourly_wage', models.IntegerField(default=0, verbose_name='バイト時給')),
                ('rent', models.IntegerField(default=0, verbose_name='家賃')),
                ('rent_renewal', models.IntegerField(default=0, verbose_name='家賃更新代')),
                ('renewal_frequency', models.IntegerField(default=0, verbose_name='家賃更新頻度/年')),
                ('yumeya_fee', models.IntegerField(default=0, verbose_name='夢屋ライセンスフィー')),
                ('utility_cost', models.IntegerField(default=0, verbose_name='光熱費')),
                ('ad_cost', models.IntegerField(default=0, verbose_name='広告費')),
                ('other_total', models.IntegerField(default=0, verbose_name='その他諸経費')),
            ],
        ),
    ]
